// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: message.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg_MSGTYPE int32

const (
	Msg_SENDMSG      Msg_MSGTYPE = 0
	Msg_VERIFYFRIEND Msg_MSGTYPE = 1
)

// Enum value maps for Msg_MSGTYPE.
var (
	Msg_MSGTYPE_name = map[int32]string{
		0: "SENDMSG",
		1: "VERIFYFRIEND",
	}
	Msg_MSGTYPE_value = map[string]int32{
		"SENDMSG":      0,
		"VERIFYFRIEND": 1,
	}
)

func (x Msg_MSGTYPE) Enum() *Msg_MSGTYPE {
	p := new(Msg_MSGTYPE)
	*p = x
	return p
}

func (x Msg_MSGTYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Msg_MSGTYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (Msg_MSGTYPE) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x Msg_MSGTYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Msg_MSGTYPE.Descriptor instead.
func (Msg_MSGTYPE) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2, 0}
}

type Sendmsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wxid    string `protobuf:"bytes,1,opt,name=wxid,proto3" json:"wxid,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Sendmsg) Reset() {
	*x = Sendmsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sendmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sendmsg) ProtoMessage() {}

func (x *Sendmsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sendmsg.ProtoReflect.Descriptor instead.
func (*Sendmsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Sendmsg) GetWxid() string {
	if x != nil {
		return x.Wxid
	}
	return ""
}

func (x *Sendmsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Verifyfriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V1 string `protobuf:"bytes,1,opt,name=v1,proto3" json:"v1,omitempty"`
	V2 string `protobuf:"bytes,2,opt,name=v2,proto3" json:"v2,omitempty"`
}

func (x *Verifyfriend) Reset() {
	*x = Verifyfriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Verifyfriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verifyfriend) ProtoMessage() {}

func (x *Verifyfriend) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verifyfriend.ProtoReflect.Descriptor instead.
func (*Verifyfriend) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Verifyfriend) GetV1() string {
	if x != nil {
		return x.V1
	}
	return ""
}

func (x *Verifyfriend) GetV2() string {
	if x != nil {
		return x.V2
	}
	return ""
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgid Msg_MSGTYPE `protobuf:"varint,1,opt,name=msgid,proto3,enum=Msg_MSGTYPE" json:"msgid,omitempty"`
	// Types that are assignable to Payload:
	//	*Msg_Sendmsg
	//	*Msg_Vefiryfriend
	Payload isMsg_Payload `protobuf_oneof:"payload"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Msg) GetMsgid() Msg_MSGTYPE {
	if x != nil {
		return x.Msgid
	}
	return Msg_SENDMSG
}

func (m *Msg) GetPayload() isMsg_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Msg) GetSendmsg() *Sendmsg {
	if x, ok := x.GetPayload().(*Msg_Sendmsg); ok {
		return x.Sendmsg
	}
	return nil
}

func (x *Msg) GetVefiryfriend() *Verifyfriend {
	if x, ok := x.GetPayload().(*Msg_Vefiryfriend); ok {
		return x.Vefiryfriend
	}
	return nil
}

type isMsg_Payload interface {
	isMsg_Payload()
}

type Msg_Sendmsg struct {
	Sendmsg *Sendmsg `protobuf:"bytes,2,opt,name=sendmsg,proto3,oneof"`
}

type Msg_Vefiryfriend struct {
	Vefiryfriend *Verifyfriend `protobuf:"bytes,3,opt,name=vefiryfriend,proto3,oneof"`
}

func (*Msg_Sendmsg) isMsg_Payload() {}

func (*Msg_Vefiryfriend) isMsg_Payload() {}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x37, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x78,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x78, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x32, 0x22, 0xb9, 0x01, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x12, 0x22, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x53, 0x47, 0x54, 0x59, 0x50, 0x45, 0x52, 0x05, 0x6d,
	0x73, 0x67, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x6d, 0x73, 0x67, 0x48,
	0x00, 0x52, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x73, 0x67, 0x12, 0x33, 0x0a, 0x0c, 0x76, 0x65,
	0x66, 0x69, 0x72, 0x79, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x48,
	0x00, 0x52, 0x0c, 0x76, 0x65, 0x66, 0x69, 0x72, 0x79, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x22,
	0x28, 0x0a, 0x07, 0x4d, 0x53, 0x47, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45,
	0x4e, 0x44, 0x4d, 0x53, 0x47, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x56, 0x45, 0x52, 0x49, 0x46,
	0x59, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_proto_goTypes = []interface{}{
	(Msg_MSGTYPE)(0),     // 0: Msg.MSGTYPE
	(*Sendmsg)(nil),      // 1: Sendmsg
	(*Verifyfriend)(nil), // 2: Verifyfriend
	(*Msg)(nil),          // 3: Msg
}
var file_message_proto_depIdxs = []int32{
	0, // 0: Msg.msgid:type_name -> Msg.MSGTYPE
	1, // 1: Msg.sendmsg:type_name -> Sendmsg
	2, // 2: Msg.vefiryfriend:type_name -> Verifyfriend
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sendmsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Verifyfriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Msg_Sendmsg)(nil),
		(*Msg_Vefiryfriend)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
